### ISSUE TITLE
Image fails due to ClassNotFoundException

### ISSUE THREAD

**Issue by locofocos** [ferrarimarco/docker-liquibase#1]
It looks like the latest build is failing.

Commit - https://github.com/ferrarimarco/docker-liquibase/commit/4302df251160e7859fdfd581926cd6c52e5a7f83
Travis build - https://travis-ci.org/ferrarimarco/docker-liquibase/builds/392589850?utm_source=github_status&utm_medium=notification

My team is consuming this image and our builds starting failing since we were pointed at the "latest" image. We get the same exception as Travis when we try to run it. I see you have an image tagged "1.0.0" of the previous build, and pointing to that has got us up and running again.

I was going to open a PR adjust the Travis config so that a failed build wouldn't get pushed (as seems to be the case, I think?). But I'm not seeing what's responsible for pushing the image. This might be a good example to pull from, if anyone makes such an enhancement: https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5

**Comment by ferrarimarco** [comment]
Hi @locofocos 

The image is automatically built on Docker Hub (see [this page](https://docs.docker.com/docker-hub/builds/) for reference).

Actually this is an upstream issue: https://liquibase.jira.com/browse/CORE-3222

Maybe I should revert to 3.5.5 (the last pre-3.6.0 version)...

**Comment by ferrarimarco** [comment]
PS: pointing to the `latest` tag leads to unreproducible builds :)

**Comment by ferrarimarco** [comment]
@locofocos I added the missing lib and refreshed the `3.6.1` and `latest` tags. Let me know if it works for you (feel free to reopen this issue or file a new one).

**Comment by locofocos** [comment]
@ferrarimarco Thanks so much! I just tested our build with the `latest` tag (running liquibase version 3.6.1) and it's working perfectly (once I corrected for a tiny API change in liquibase - the "success" message).

Appreciate your maintenance on this too!
